general:
  bind: "0.0.0.0"
  port: 1080
  log_level: "info"
  log_format: "text"
  health_check_interval: 30s
  chain_cleanup_interval: 10m
  health_check_timeout: 5s
  health_check_concurrency: 10
  io_timeout: 5s

chains:
  - username: "user"
    password: "pass"
    chain:
      - name: "proxy1"
        username: "puser"
        password: "ppass"
        host: "proxy1.example"
        port: 1080
      - strategy: "rr"
        proxies:
          - name: "proxy2"
            username: "puser2"
            password: "ppass2"
            host: "proxy2.example"
            port: 1080
          - name: "proxy3"
            username: "puser3"
            password: "ppass3"
            host: "proxy3.example"
            port: 1080
